import { auth, ClerkProvider, currentUser } from '@clerk/nextjs'
import { UserButton } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from './components/Footer';
import Header from './components/Header';
import { sql} from "@vercel/postgres";
import CreateProfile from './components/CreateProfile';
import Link from 'next/link';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { userId } = auth();
  const profileRes =await sql`SELECT * FROM profiles WHERE clerk_user_id = ${userId}`;
  console.log(profileRes);

  // const user = await currentUser

  return (
    <ClerkProvider>

    <html lang="en">
      <body className={inter.className}>
        <Header />
        {userId && <UserButton afterSignOutUrl="/" />}
        {profileRes.rowCount !== 0 && children}
        {/* {userId && <Link href="/sign-in">Sign In</Link>} */}
        {profileRes.rowCount === 0 && <CreateProfile />}
        <Footer />
        </body>
    </html>
    </ClerkProvider>
  );
}
